DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
DEBUG:pymongo.ocsp_support:OCSP response status: <OCSPResponseStatus.SUCCESSFUL: 0>
DEBUG:pymongo.ocsp_support:OCSP response status: <OCSPResponseStatus.SUCCESSFUL: 0>
DEBUG:pymongo.ocsp_support:Verifying response
DEBUG:pymongo.ocsp_support:Verifying response
DEBUG:pymongo.ocsp_support:Responder is issuer
DEBUG:pymongo.ocsp_support:Responder is issuer
DEBUG:pymongo.ocsp_support:Caching OCSP response.
DEBUG:pymongo.ocsp_support:Caching OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
DEBUG:pymongo.ocsp_support:OCSP response status: <OCSPResponseStatus.SUCCESSFUL: 0>
DEBUG:pymongo.ocsp_support:Verifying response
DEBUG:pymongo.ocsp_support:Responder is issuer
DEBUG:pymongo.ocsp_support:Caching OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:pymongo.ocsp_support:Using cached OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:pymongo.ocsp_support:Using cached OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:pymongo.ocsp_support:Using cached OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
ERROR:root:
System: Windows
Node: DESKTOP-4HHR1F9
Release: 10
Version: 10.0.22621
Machine: AMD64
Processor: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
Total RAM: 6323187712 bytes
Available RAM: 919158784 bytes
RAM Usage: 85.5%

ERROR:root:Critical error: Data corruption
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "D:\Hackathon\Crasheye_backend\Test\new_try\generate_crash.py", line 92, in <module>
    generate_random_crash()
  File "D:\Hackathon\Crasheye_backend\Test\new_try\generate_crash.py", line 81, in generate_random_crash
    critical_error(system_info)
  File "D:\Hackathon\Crasheye_backend\Test\new_try\generate_crash.py", line 33, in critical_error
    raise Exception("Data corruption")
Exception: Data corruption
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:pymongo.ocsp_support:Using cached OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
